import { isSolid } from './terrain.js';
import type { Terrain, WeaponDef, WeaponKey, Worm, RaycastHit, ProjectileIntegration, Vector2 } from './types.js';

// Weapons with a cap on total uses per team per match - absent keys mean no
// limit. Checked/decremented per-team in matchLoop.ts's stepMatch.
export const WEAPON_MATCH_LIMITS: Partial<Record<WeaponKey, number>> = {
  airstrikeRocket: 1,
  holyHandGrenade: 2,
};

export const WEAPONS: Record<WeaponKey, WeaponDef> = {
  bazooka: {
    key: 'bazooka',
    maxDamage: 60,
    blastRadius: 40,
    craterRadius: 40,
    chargeable: true,
    minSpeed: 250,
    maxSpeed: 1100,
    gravity: true,
    windAffected: true,
    fuseTime: null,
    hitscan: false,
    pellets: 0,
    bounces: false,
    rope: false,
    airstrike: false,
    drill: false,
    melee: false,
    homing: false,
  },
  grenade: {
    key: 'grenade',
    maxDamage: 50,
    blastRadius: 45,
    craterRadius: 45,
    chargeable: true,
    minSpeed: 150,
    maxSpeed: 900,
    gravity: true,
    windAffected: true,
    fuseTime: 3.5,
    hitscan: false,
    pellets: 0,
    bounces: true,
    rope: false,
    airstrike: false,
    drill: false,
    melee: false,
    homing: false,
  },
  shotgun: {
    key: 'shotgun',
    maxDamage: 25,
    blastRadius: 10,
    craterRadius: 10,
    chargeable: false,
    minSpeed: 0,
    maxSpeed: 0,
    gravity: false,
    windAffected: false,
    fuseTime: null,
    hitscan: true,
    pellets: 2,
    bounces: false,
    rope: false,
    airstrike: false,
    drill: false,
    melee: false,
    homing: false,
    range: 500,
  },
  ninjaRope: {
    key: 'ninjaRope',
    maxDamage: 0,
    blastRadius: 0,
    craterRadius: 0,
    chargeable: false,
    minSpeed: 500,
    maxSpeed: 500,
    gravity: false,
    windAffected: false,
    fuseTime: null,
    hitscan: false,
    pellets: 0,
    bounces: false,
    rope: true,
    airstrike: false,
    drill: false,
    melee: false,
    homing: false,
    range: 400,
  },
  dynamite: {
    key: 'dynamite',
    maxDamage: 75,
    blastRadius: 60,
    craterRadius: 60,
    chargeable: false,
    minSpeed: 0,
    maxSpeed: 0,
    gravity: true,
    windAffected: false,
    fuseTime: 3,
    hitscan: false,
    pellets: 0,
    bounces: false,
    rope: false,
    airstrike: false,
    drill: false,
    melee: false,
    homing: false,
  },
  sniperRifle: {
    key: 'sniperRifle',
    maxDamage: 45,
    blastRadius: 10,
    craterRadius: 10,
    chargeable: false,
    minSpeed: 0,
    maxSpeed: 0,
    gravity: false,
    windAffected: false,
    fuseTime: null,
    hitscan: true,
    pellets: 1,
    bounces: false,
    rope: false,
    airstrike: false,
    drill: false,
    melee: false,
    homing: false,
    range: 1000,
  },
  airstrikeRocket: {
    key: 'airstrikeRocket',
    maxDamage: 36,
    blastRadius: 60,
    craterRadius: 40,
    chargeable: false,
    minSpeed: 0,
    maxSpeed: 0,
    gravity: false,
    windAffected: false,
    fuseTime: null,
    hitscan: false,
    pellets: 0,
    bounces: false,
    rope: false,
    airstrike: true,
    drill: false,
    melee: false,
    homing: false,
  },
  holyHandGrenade: {
    key: 'holyHandGrenade',
    maxDamage: 125,
    blastRadius: 130,
    craterRadius: 130,
    chargeable: true,
    minSpeed: 150,
    maxSpeed: 650,
    gravity: true,
    windAffected: true,
    fuseTime: 6,
    hitscan: false,
    pellets: 4,
    bounces: true,
    rope: false,
    airstrike: false,
    drill: false,
    melee: false,
    homing: false,
  },
  mine: {
    key: 'mine',
    maxDamage: 70,
    blastRadius: 55,
    craterRadius: 55,
    chargeable: false,
    minSpeed: 0,
    maxSpeed: 0,
    gravity: true,
    windAffected: false,
    fuseTime: 10,
    hitscan: false,
    pellets: 0,
    bounces: false,
    rope: false,
    airstrike: false,
    drill: false,
    melee: false,
    homing: false,
  },
  drill: {
    key: 'drill',
    maxDamage: 0,
    blastRadius: 0,
    craterRadius: 16,
    chargeable: false,
    minSpeed: 0,
    maxSpeed: 0,
    gravity: false,
    windAffected: false,
    fuseTime: null,
    hitscan: false,
    pellets: 0,
    bounces: false,
    rope: false,
    airstrike: false,
    drill: true,
    melee: false,
    homing: false,
    range: 120,
  },
  homingMissile: {
    key: 'homingMissile',
    maxDamage: 55,
    blastRadius: 45,
    craterRadius: 45,
    chargeable: true,
    minSpeed: 250,
    maxSpeed: 700,
    gravity: false,
    windAffected: false,
    fuseTime: null,
    hitscan: false,
    pellets: 0,
    bounces: false,
    rope: false,
    airstrike: false,
    drill: false,
    melee: false,
    homing: true,
  },
  clusterBomb: {
    key: 'clusterBomb',
    maxDamage: 15,
    blastRadius: 25,
    craterRadius: 25,
    chargeable: true,
    minSpeed: 150,
    maxSpeed: 750,
    gravity: true,
    windAffected: true,
    fuseTime: null,
    hitscan: false,
    pellets: 0,
    bounces: false,
    rope: false,
    airstrike: false,
    drill: false,
    melee: false,
    homing: false,
    clusterCount: 5,
  },
  clusterFragment: {
    key: 'clusterFragment',
    maxDamage: 18,
    blastRadius: 35,
    craterRadius: 20,
    chargeable: false,
    // Not used to compute launch speed (fragments get an explicit vx/vy at
    // spawn time, see Task 3) - kept nonzero only so
    // hasActiveStaticFuseProjectile's `minSpeed === 0 && maxSpeed === 0`
    // check in matchLoop.ts can't misclassify a fragment as a static-fuse
    // drop like the mine/dynamite.
    minSpeed: 150,
    maxSpeed: 350,
    gravity: true,
    windAffected: true,
    fuseTime: 1.1,
    hitscan: false,
    pellets: 0,
    bounces: false,
    rope: false,
    airstrike: false,
    drill: false,
    melee: false,
    homing: false,
  },
  bat: {
    key: 'bat',
    maxDamage: 30,
    blastRadius: 0,
    craterRadius: 0,
    chargeable: false,
    minSpeed: 0,
    maxSpeed: 0,
    gravity: false,
    windAffected: false,
    fuseTime: null,
    hitscan: false,
    pellets: 0,
    bounces: false,
    rope: false,
    airstrike: false,
    drill: false,
    melee: true,
    homing: false,
    range: 55,
  },
};

export function integrateProjectile(
  pos: Vector2,
  vel: Vector2,
  gravity: number,
  wind: number,
  dt: number,
): ProjectileIntegration {
  const nvx = vel.x + wind * dt;
  const nvy = vel.y + gravity * dt;
  return {
    pos: { x: pos.x + nvx * dt, y: pos.y + nvy * dt },
    vel: { x: nvx, y: nvy },
  };
}

export function calcDamage(distance: number, blastRadius: number, maxDamage: number): number {
  if (blastRadius <= 0) return distance <= 0 ? maxDamage : 0;
  if (distance >= blastRadius) return 0;
  const falloff = 1 - distance / blastRadius;
  return Math.round(maxDamage * falloff);
}

export function raycastHit(
  terrain: Terrain,
  worms: Worm[],
  originX: number,
  originY: number,
  angle: number,
  maxRange: number,
  excludeWorm?: Worm,
): RaycastHit {
  const dx = Math.cos(angle);
  const dy = Math.sin(angle);
  const step = 2;
  for (let d = 0; d <= maxRange; d += step) {
    const x = originX + dx * d;
    const y = originY + dy * d;
    const hitWorm = worms.find((w) => w.alive && !w.dying && w !== excludeWorm && Math.hypot(w.x - x, w.y - y) < 10);
    if (hitWorm) return { type: 'worm', worm: hitWorm, x, y, distance: d };
    if (isSolid(terrain, x, y)) return { type: 'terrain', x, y, distance: d };
  }
  return { type: 'none', x: originX + dx * maxRange, y: originY + dy * maxRange, distance: maxRange };
}
